runtime: nodejs22
instance_class: F1
env_variables:
  SENDGRID_API_KEY: "{SENDGRID_API_KEY}"
automatic_scaling:
  max_instances: 1
handlers:
  - url: /.*
    secure: always
    redirect_http_response_code: 301
    script: auto